<?php

return [
    'app'                   => [
        'title' => 'General',
        'desc'  => 'All the general settings for application.',
        'icon'  => 'glyphicon glyphicon-sunglasses',
    ],
    'general_settings'      => [
        'elements' => [
            [
                'type'     => 'text',
                'name'     => 'address_line1',
                'label'    => 'Address Line 1',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'address_line2',
                'label'    => 'Address Line 2',
                'class'    => '',
                'rules'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'country',
                'label'    => 'Country',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'state',
                'label'    => 'State',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'city',
                'label'    => 'City',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],

            [
                'type'     => 'text',
                'name'     => 'zipcode',
                'label'    => 'Zipcode',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'mobile_no',
                'label'    => 'Contact Number',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'email',
                'label'    => 'Email',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'fax',
                'label'    => 'Fax',
                'rules'    => 'required',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'toll_free_number',
                'label'    => 'Toll Free Number',
                'rules'    => 'required',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'textarea',
                'name'     => 'working_hours',
                'label'    => 'Working Hours',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'       => 'text',
                'name'       => 'currency_name',
                'label'      => 'Currency Name',
                'rules'      => 'required',
                'class'      => '',
                'classClear' => 1,
                'required'   => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'currency_code',
                'label'    => 'Currency Code',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'currency_symbol',
                'label'    => 'Currency Symbol',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'       => 'text',
                'name'       => 'weight_in',
                'label'      => 'Weight In',
                'rules'      => 'required',
                'class'      => '',
                'classClear' => 1,
                'required'   => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'depth_in',
                'label'    => 'Depth In',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'height_in',
                'label'    => 'Height In',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'width_in',
                'label'    => 'Width In',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'       => 'text',
                'name'       => 'contact_notification_email',
                'label'      => 'Contact Us Notification Email',
                'rules'      => 'required',
                'class'      => '',
                'classClear' => 1,
                'required'   => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'from_email',
                'label'    => 'From Email',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'from_name',
                'label'    => 'From Name',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'       => 'text',
                'name'       => 'admin_notification_email',
                'label'      => 'Order Notification Email',
                'rules'      => 'required',
                'class'      => '',
                'classClear' => '',
                'required'   => true,
            ],
            [
                'type'       => 'radio',
                'name'       => 'apply_coupon',
                'label'      => 'Apply Coupon',
                'classClear' => 1,
                'data'       => 'boolean',
                'value'      => 0,
                'class'      => '',
                'options'    => [
                    1 => 'Enable',
                    0 => 'Disable',
                ],
            ],
        ],
    ],
    'product_settings'      => [
        'elements' => [
            [
                'type'    => 'radio',
                'label'   => 'Quick Product view',
                'name'    => 'quick_product_view',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            // [
            //     'type' => 'radio',
            //     'label' => 'Compare Products Option',
            //     'name' => 'compare_products_option',
            //     'data' => 'boolean',
            //     'value' => 0,
            //     'class' => '',
            //     'options' => [
            //         1 => 'Yes',
            //         0 => 'No'
            //     ]
            // ],
            [
                'type'    => 'radio',
                'label'   => 'Wish List in the frontend',
                'name'    => 'wish_list_in_the_frontend',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'Featured Products on Home Page',
                'name'    => 'featured_products_on_home_page',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'Featured Tag on Products listing',
                'name'    => 'featured_tag_on_products_listing',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'New Products on Home Page',
                'name'    => 'new_products_on_home_page',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'New Products Tags on Products listing',
                'name'    => 'new_products_tags_on_products_listing',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'Top Selling Products on Home Page',
                'name'    => 'top_selling_products_on_home_page',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'Related Products on Product Detail Page',
                'name'    => 'related_products_on_product_detail_page',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            // [
            //     'type'    => 'radio',
            //     'label'   => 'Reviews/Rating on Product Detail Page',
            //     'name'    => 'reviews_rating_on_product_detail_page',
            //     'data'    => 'boolean',
            //     'value'   => 0,
            //     'class'   => '',
            //     'options' => [
            //         1 => 'Yes',
            //         0 => 'No',
            //     ],
            // ],
        ],
    ],
    'social_media_settings' => [
        'elements' => [
            [
                'type'     => 'text',
                'name'     => 'facebook_link',
                'label'    => 'Facebook Link',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'twitter_link',
                'label'    => 'Twitter Link',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'dribbble_link',
                'label'    => 'Dribbble Link',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'youtube_link',
                'label'    => 'Youtube Link',
                'class'    => '',
                'required' => false,
            ],
        ],
    ],
    'review_settings'       => [
        'elements' => [
            [
                'type'    => 'radio',
                'label'   => 'User Can Write Reviews If',
                'name'    => 'user_allowed_review',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    0 => 'Guest User',
                    1 => 'Logged In User',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'Display Reviews on Frontend',
                'name'    => 'display_reviews_frontend',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    0 => 'No',
                    1 => 'Yes',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => 'Default Status of Reviews submitted by users',
                'name'    => 'default_user_review_status',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    0 => 'Disapproved',
                    1 => 'Approved',
                ],
            ],
        ],
    ],
    'payment_settings'      => [
        'elements' => [
            [
                'type'    => 'radio',
                'label'   => '',
                'name'    => 'payment_mode',
                'data'    => 'boolean',
                'value'   => '',
                'class'   => '',
                'options' => [
                    0 => 'Sandbox Mode',
                ],
            ],
            [
                'type'    => 'radio',
                'label'   => '',
                'name'    => 'payment_mode',
                'data'    => 'boolean',
                'value'   => '',
                'class'   => '',
                'options' => [
                    1 => 'Live Mode',
                ],
            ],
            [
                'type'  => 'text',
                'name'  => 'sandbox_login_id',
                'label' => 'Sandbox API Login ID',
                'class' => '',
            ],
            [
                'type'  => 'text',
                'name'  => 'live_login_id',
                'label' => 'Live API Login ID',
                'class' => '',
            ],
            [
                'type'  => 'text',
                'name'  => 'sandbox_transaction_key',
                'label' => 'Sandbox Transaction Key',
                'class' => '',
            ],
            [
                'type'  => 'text',
                'name'  => 'live_transaction_key',
                'label' => 'Live Transaction Key',
                'class' => '',
            ],
        ],
    ],
    'sds_settings'          => [
        'elements' => [
            [
                'type'     => 'text',
                'name'     => 'sds_link',
                'label'    => 'Link',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'sds_user_name',
                'label'    => 'User Name',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'sds_password',
                'label'    => 'Password',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'sds_email',
                'label'    => 'Email',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'sds_notification_email',
                'label'    => 'SDS Notification Email',
                'class'    => '',
                'required' => true,
            ],
        ],
    ],
    'mail_chimp_settings'   => [
        'elements' => [
            [
                'type'     => 'text',
                'name'     => 'mail_chimp_api_key',
                'label'    => 'Api Key',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'mail_chimp_list_id',
                'label'    => 'List Id',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'mail_chimp_unsubscribe_link',
                'label'    => 'Unsubscribe Link',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
        ],
    ],
    'seo_settings'          => [
        'elements' => [
            [
                'type'     => 'text',
                'name'     => 'default_meta_title',
                'label'    => 'Default Title',
                'rules'    => 'nullable',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'default_meta_keywords',
                'label'    => 'Default Meta Keywords',
                'class'    => '',
                'rules'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'default_meta_description',
                'label'    => 'Default Meta Description',
                'rules'    => '',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'    => 'radio',
                'label'   => 'Index Website on Search engine',
                'name'    => 'index_website_on_search_engine',
                'data'    => 'boolean',
                'value'   => 0,
                'class'   => '',
                'options' => [
                    1 => 'Yes',
                    0 => 'No',
                ],
            ],
            [
                'type'       => 'textarea',
                'name'       => 'robots_txt',
                'label'      => 'Robots.txt',
                'rules'      => 'required',
                'class'      => '',
                'classClear' => 1,
                'required'   => false,
            ],
            [
                'type'       => 'text',
                'name'       => 'webmaster_tags_google',
                'label'      => 'Google Webmaster Id',
                'rules'      => '',
                'class'      => '',
                'classClear' => 1,
                'required'   => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'webmaster_tags_bing',
                'label'    => 'Bing Webmaster Id',
                'rules'    => '',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'webmaster_tags_alexa',
                'label'    => 'Alexa Webmaster Id',
                'rules'    => '',
                'class'    => '',
                'required' => false,
            ],
            [
                'type'     => 'text',
                'name'     => 'webmaster_google_analytics',
                'label'    => 'Google Analytics Id',
                'rules'    => '',
                'class'    => '',
                'required' => false,
            ],
        ],
    ],
    'email_settings'   => [
        'elements' => [
            [
                'type'     => 'text',
                'name'     => 'email_host',
                'label'    => 'Host',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'email_port',
                'label'    => 'Port',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'email_username',
                'label'    => 'Username',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'email_password',
                'label'    => 'Password',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'email_from_email',
                'label'    => 'From Email',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
            [
                'type'     => 'text',
                'name'     => 'email_from_name',
                'label'    => 'From Name',
                'rules'    => 'required',
                'class'    => '',
                'required' => true,
            ],
        ],
    ],
];
